import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarDemo } from "@/components/dashborad";
import { Toaster } from "@/components/ui/toaster";
import { WalletProvider } from '@/context/wallet-context';  // Add this import

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletProvider>  {/* Add this line */}
          {children}
          <Toaster/>
        </WalletProvider>  {/* And this line */}
      </body>
    </html>
  );
}